---
  - hosts: vm_instances
    become: true
    tasks:
    - name: Update apt packages
      apt: upgrade=yes update_cache=yes
      when: ansible_facts['os_family'] == "Debian"
    - name: "Install PXE TFTP utilities"
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - apache2
        - dnsmasq
    - name: "Checking folders"
      stat:
       path: "{{item}}"
      register: folder_stats
      with_items:
      - ["/var/lib/tftpboot/pxelinux.cfg"]
    - name: "Create directory structure"
      file:
        path: "{{item.item}}"
        state: directory
        mode: '0755'
      when: item.stat.exists == false
      with_items:
      - "{{folder_stats.results}}"
    - name: "Copy kernel"
      copy:
        src: images/kernel-x86_64-pc99
        dest: /var/lib/tftpboot/kernel-x86_64-pc99
    - name: "Copy initrd"
      copy:
        src: images/apps-x86_64-pc99
        dest: /var/lib/tftpboot/apps-x86_64-pc99
    - name: "Copy pxe config"
      copy:
        src: pxelinux.cfg/default
        dest: /var/lib/tftpboot/pxelinux.cfg/default
    - name: "Copy bootloader"
      copy:
        src: mboot.c32
        dest: /var/lib/tftpboot/mboot.c32
